<!-- Card.svelte -->
<script lang="ts">
	import type { ImportGlobEagerFunction } from "vite";


    // export let title:string;
    // export let content:string;
    export let imageSrc:string;
    export let imageSrcLogo:string;

    console.log(imageSrcLogo);
console.log(imageSrc);
  </script>
  
  <div class="   relative sm:w-auto flex shadow-2xl rounded-md ">
  
    <div class="z-[1] logo flex justify-center items-center w-[100%] h-[100%]  hover:bg-gradient-to-r from-blue-900 to-red-900 opacity-75 ">
      <img class="h-[10rem] w-[10rem] slide-top " src={imageSrcLogo} alt="/">

    </div>
    
    <div class="eapl-game-box__background-link ">
      <img class="  " src={imageSrc} alt="/"> 
    </div>
  </div>
  <style>


.logo{
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  
  justify-content: center;
  z-index: 2;
}

.eapl-game-box__background-link {
  
  position: relative;
  z-index: 0;
  height: inherit;
  width: inherit;
  /* opacity: 0.3;   */
  /* background: black; */

  }

/* ----------------------------------------------
 * Generated by Animista on 2023-6-2 13:35:1
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
 @-webkit-keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-100px);
            transform: translateY(-100px);
  }
}
@keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-100px);
            transform: translateY(-100px);
  }
}


.slide-top:hover {
	-webkit-animation: slide-top 0.5s ease-out both;
	        animation: slide-top 0.5s ease-out both;
}




   </style>